### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by MagikModder** [BurntRouter/StevesUniverse#2]
I might be wrong but this looks exactly like my code;)

**Comment by BurntRouter** [comment]
What?

**Comment by MagikModder** [comment]
https://github.com/MagikModder/StevenUniverseMod

**Comment by BurntRouter** [comment]
Your point?

**Comment by MagikModder** [comment]
"I might be wrong but this looks exactly like my code ;)"

**Comment by BurntRouter** [comment]
Considering Polar and I wrote all of this code and I wrote the majority of it, I can promise you it's not.

**Comment by MagikModder** [comment]
I noticed. Considering you have 40 commits and he only has 13, i would say you have a great team ;)

**Comment by BurntRouter** [comment]
They're pretty good

**Comment by MagikModder** [comment]
I'll bet. Just a question, what is the purpose of having the gems (Items) in the mod if they don't do anything?

**Comment by BurntRouter** [comment]
They're works in progress...

**Comment by BurntRouter** [comment]
Since when is this how JavaBuckets operates?

**Comment by MagikModder** [comment]
I can tell.

**Comment by BurntRouter** [comment]
I've never seen anybody from JavaBuckets complain about my code. They do know me.

**Comment by MagikModder** [comment]
Thom doesn't know you...

**Comment by BurntRouter** [comment]
Tell him I'm Koslaw99

**Comment by MagikModder** [comment]
"Since when is this how JavaBuckets operates? "

Javabuckets has been down the last couple weeks, personal stuff

**Comment by BurntRouter** [comment]
Well you reflect badly on the team just saying.
