### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by MineRobber9000** [BurntRouter/StevesUniverse#4]
How exactly do you build this mod? The README just says that it's passing the build test, and gives the legal copyright.

**Comment by BurntRouter** [comment]
I just updated it. I hope it's clear enough, I'm writing this from school on my phone so it was a bit rushed but it sounds good to me. If you have any problems please let me know.

**Comment by MineRobber9000** [comment]
What version of Minecraft is this mod for?

**Comment by BurntRouter** [comment]
It's for 1.7.10. I was going to work on a 1.8 version but my computer is broken until Tuesday.

**Comment by MineRobber9000** [comment]
ok

**Comment by BurntRouter** [comment]
Yeah sorry.

**Comment by MineRobber9000** [comment]
trying it out now as a matter of fact :P
