### ISSUE TITLE
invisible mobs

### ISSUE THREAD

**Issue by jgyft** [BurntRouter/StevesUniverse#5]
whenever I try to use the mod all the mobs turn invisible as in I can't see or interact with any of the mobs but I know they're there because ruby and sapphire still leaves trails of ashes and snow behind them I just can't see them

**Comment by BurntRouter** [comment]
Can you please post your game log.
What version of the mod are you using?
What version of forge are you using?
Have you tried reinstalling the mod?

**Comment by jgyft** [comment]
I'm using version 1.0.2
I'm using Forge10.13.4.1490-1.7.10
I've reinstalled the mod at least 3 times and it always ends up with the same results
here is a link to a pastebin of the server log http://pastebin.com/wjRTgTbV

**Comment by BurntRouter** [comment]
Closed. Issue found and fixed in ATimeMod 2 in V1.0 (not yet public)
